### PR TITLE
improve start/stop vm

### PR DESCRIPTION
**Pull request by marco-hoyer**
track task state and handle errors,
add idempotency (no errors for already started/stopped vms)

### CODE REVIEW

**Comment by marco-hoyer** [comment]
Hi Max, I thought about using it for esx tasks as well but we don't need it right now. I will have a look at this thirdparty thing and maybe rethink the implementation if we go on automating stuff. Thanks for the advice. :-)

**Comment by mriehl** [comment]
Travis has a flake8 complaint, care to fix it?

```
[WARN]  flake8: src/unittest/python/command_tests.py:475:104: W292 no newline at end of file
```

**Comment by marco-hoyer** [comment]
sure! ;-)

**Comment by marco-hoyer** [comment]
done :-)

**Comment by mriehl** [comment]
Great additions, thanks!

**Pull request merged**
